image: node:16

definitions:
  caches:
    npm: ~/.npm
    
  steps:
    - step: &build-and-test
        name: Build and Test
        caches:
          - npm
        script:
          - npm ci
          - NODE_OPTIONS='--experimental-vm-modules' npm test
          
    - step: &deploy-to-dev
        name: Deploy to Dev
        deployment: Dev
        caches:
          - npm
        script:
          # Install AWS CLI
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip awscliv2.zip
          - ./aws/install
          
          # Configure AWS credentials
          - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          - aws configure set region $AWS_DEFAULT_REGION
              
          # Install dependencies and build
          - npm ci
          - npm run build
          
          # Deploy to S3
          - aws s3 sync dist/ s3://digi-surakshaa-dev --delete
          
          # Invalidate CloudFront cache
          - aws cloudfront create-invalidation --distribution-id $CF_DEV_DISTRIBUTION_ID --paths "/*"
          
    - step: &deploy-to-prod
        name: Deploy to Production
        deployment: Production
        caches:
          - npm
        script:
          # Install AWS CLI
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip awscliv2.zip
          - ./aws/install
          
          # Configure AWS credentials
          - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          - aws configure set region $AWS_DEFAULT_REGION
              
          # Install dependencies and build
          - npm ci
          - npm run build
          
          # Deploy to S3
          - aws s3 sync dist/ s3://digi-surakshaa-prod --delete
          
          # Invalidate CloudFront cache
          - aws cloudfront create-invalidation --distribution-id $CF_PROD_DISTRIBUTION_ID --paths "/*"

pipelines:
  default:
    - parallel:
      - step: *build-and-test
      
  branches:
    dev:
      - parallel:
        - step: *build-and-test
      - step: *deploy-to-dev
        
    main:
      - parallel:
        - step: *build-and-test
      - step: *deploy-to-prod

  pull-requests:
    '**':
      - parallel:
        - step: *build-and-test

options:
  max-time: 30 