image: node:16

pipelines:
  branches:
    staging:
      - step:
          name: Build and Deploy to Vercel
          caches:
            - node
          script:
            - npm install -g vercel
            - npm install
            - npm run build
            - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
            - vercel build --token=$VERCEL_TOKEN
            - vercel deploy --prebuilt --token=$VERCEL_TOKEN --prod

definitions:
  caches:
    node: $HOME/.npm 