image: node:18

definitions:
  steps:
    - step: &build-test
        name: Build and Test
        caches:
          - node
        script:
          - node --version
          - npm --version
          - npm install
          - npm run build
        artifacts:
          - dist/**

pipelines:
  branches:
    staging:
      - step: *build-test
      - step:
          name: Deploy to Vercel
          script:
            - npm install --global vercel
            - vercel --version
            - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
            - vercel build --token=$VERCEL_TOKEN
            - vercel deploy --prebuilt --token=$VERCEL_TOKEN --prod
          artifacts:
            - .vercel/**

  pull-requests:
    '**':
      - step: *build-test

options:
  max-time: 30

definitions:
  caches:
    node: $HOME/.npm 